version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exweb
    ports:
      - "5433:5432"
    volumes:
      - exweb_pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      # Fallback if not provided in env file
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/exweb
      - JWT_SECRET=change_me_please
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - db
    ports:
      - "8001:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_BACKEND_URL=http://backend:8000
      - VITE_API_BASE_URL=/api/v1
      - VITE_ADMIN_USERNAME=admin
      - VITE_ADMIN_PASSWORD=admin
    depends_on:
      - backend
    ports:
      - "3001:3000"
    restart: unless-stopped

volumes:
  exweb_pgdata:
