FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package.json ./
RUN npm install --legacy-peer-deps

# Copy source
COPY . .

EXPOSE 3000

ENV VITE_BACKEND_URL=http://backend:8000

CMD ["npm", "run", "dev"]
